### ISSUE TITLE
Facebook share image?

### ISSUE THREAD

**Issue by davehakkens** [hakkens/hopper#16]
Got this on twitter. I don't use Facebook but seems he makes a good point. possible?

@davehakkens love your new project. Could you add some hidden thumbnails/preview so that when you share it on facebook it's not just a link?

**Comment by leo** [comment]
Which one do you want me to add? 500x500 (png) is okay. - You can upload it here if you want.

**Comment by davehakkens** [comment]
![facebook-picca](https://cloud.githubusercontent.com/assets/13672737/10293440/c831e64a-6bb4-11e5-8fd0-4d8ff5ba83c1.png)

**Comment by leo** [comment]
Was added in e3773c8!
