### ISSUE TITLE
Find a way to share large start-kit file

### ISSUE THREAD

**Issue by davehakkens** [hakkens/hopper#19]
Couldn't increase my upload limit. Need to find another way to include a large file.

**Comment by leo** [comment]
Have you already tried contacting your web hoster? Because they're definitely able to adjust this if you tell them to change your "WordPress upload limit".

It seems like we're not able to do this directly on the webspace.

**Comment by leo** [comment]
Since your hoster won't change PHP's upload limit, we'll have to do it with an external URL. Send me the URL and I'll implement it.
