### ISSUE TITLE
Description in google search

### ISSUE THREAD

**Issue by davehakkens** [hakkens/hopper#23]
Description looks weird in Google. How to change this? Install yoast SEO plugin?

<img width="538" alt="schermafbeelding 2015-12-24 om 00 21 59" src="https://cloud.githubusercontent.com/assets/13672737/11986844/d417c61a-a9d4-11e5-8ac3-a53817348383.png">

**Comment by leo** [comment]
Haha, no. We don't need that big plugin for such a simple task. I'll implement a field that contains the site's description for you :blush:

**Comment by davehakkens** [comment]
Brilliant!

**Comment by leo** [comment]
Now the content of "Tagline" is being loaded:

<img width="679" alt="screen shot 2016-01-02 at 17 02 43" src="https://cloud.githubusercontent.com/assets/6170607/12075028/b685815a-b172-11e5-8f97-3fea0225ffbd.png">
