### ISSUE TITLE
Previous/ Next button while watching video

### ISSUE THREAD

**Issue by davehakkens** [hakkens/hopper#7]
Can we add a little button and the left and right of each video to go to the next or previous video, In this way you can keep watching videos without going back and fort to the homepage.

**Comment by davehakkens** [comment]
![example](https://cloud.githubusercontent.com/assets/13672737/10290211/0add447e-6ba3-11e5-81e3-3d91934679ae.jpg)

**Comment by leo** [comment]
Okay, now we know how the buttons will look like, perfect! But how will the action look like? What will exactly happen as soon as a user clicks on one of those buttons?

**Comment by davehakkens** [comment]
Right got to next, left to te previous video? And them preferably from the same category as you are currently looking at on the homepage. So it makes sense which movie comes next.

**Comment by leo** [comment]
@davehakkens Hehe, yep. I've already understood what you want it to do. But what we still need to think about is how the transition between the current movie and the next/previous movie will work. There are many ways to do this:

1. Close the detail view and open it with the next/previous video?
2. Just replace the video, the title and the rating

Those are just examples. What do you think?

**Comment by davehakkens** [comment]
Ah like that.
Preferably the “light” one. That uses little CPU. Like it when this goes quick.
Not sure which one that is, but probably with little transitions.  




Op dinsdag 6 oktober 2015, om 22:01 heeft Leonard het volgende geschreven:

**Comment by leo** [comment]
Okay!

But just so you know: You could develop a whole game with thousands of JavaScript effects on your site before a regular device starts lagging. Please don't worry about speed.

I guess I will fade both the title, the movie and the rating out and fade them back in as soon as the next/previous video was set.
